# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-30 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minierp_app', '0002_remove_purchase_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
