# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-01 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minierp_app', '0003_auto_20170330_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=3)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_name',
            field=models.CharField(max_length=30),
        ),
    ]
