# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-02 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minierp_app', '0006_auto_20170402_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='fax',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
