# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-02 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minierp_app', '0007_auto_20170402_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='purchase',
            new_name='buy',
        ),
    ]
