# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-02 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minierp_app', '0009_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimention',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
