# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-02 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minierp_app', '0010_auto_20170402_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
