# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-16 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minierp_app', '0011_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='note',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='note',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, upload_to='products'),
        ),
    ]
