# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-23 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minierp_app', '0015_auto_20170423_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='purchaseOrder',
        ),
    ]
