# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-30 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minierp_app', '0023_exportorder_orderitem_pendingorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=15)),
                ('price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minierp_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='PendingPurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_amount', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minierp_app.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='exportorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='exportorder',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='importorder',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='importorder',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='pendingorderitem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='pendingorderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='pendingpurchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='pendingpurchase',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExportOrder',
        ),
        migrations.DeleteModel(
            name='ImportOrder',
        ),
        migrations.DeleteModel(
            name='PendingOrderItem',
        ),
        migrations.DeleteModel(
            name='PendingPurchase',
        ),
    ]
