# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-01 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minierp_app', '0025_pendingorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
    ]
